djangoproject/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('landing.urls')),
    path('users/', include('users.urls')),
    path('materials/', include('materials.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

djangoproject/landing/urls.py
from django.urls import path 
from . import views

app_name = 'landing'

urlpatterns = [
    path('' , views.index , name='index'),    
]

djangoproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('manage_staff/', views.manage_staff, name='manage_staff'),
    path('manage_staff/<int:user_id>/', views.manage_staff, name='manage_staff_detail'),
]

djangoproject/templates/comming_soon.html
{% extends 'landing/index.html' %}
{% load static %}

{% block content %}
<div class="colorlib-about">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center colorlib-heading animate-box">
                <h2>Sección en Desarrollo</h2>
                <span class="dev-logo dev-logo-animated"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center animate-box">
                <div class="about-desc">
                    <h3>¡Estamos trabajando en esta sección!</h3>
                    <p>Nuestro equipo está desarrollando esta funcionalidad para ofrecerte una mejor experiencia.</p>
                    <p>Estará disponible en próximas actualizaciones.</p>
                    
                    <div class="row" style="margin-top: 40px;">
                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <a href="{% url 'landing:index' %}" class="btn btn-primary btn-block under-dev-link">
                                <span class="section-logo home"></span>
                                Página Principal
                            </a>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <a href="{% url 'landing:index' %}#proyectos" class="btn btn-primary btn-block under-dev-link">
                                <span class="section-logo products"></span>
                                Nuestros Productos
                            </a>
                        </div>
                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <a href="{% url 'landing:index' %}#contact" class="btn btn-primary btn-block under-dev-link">
                                <span class="section-logo contact"></span>
                                Contacto
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}